<?php

function db_menu()
{
    return array
    (
        "admin/config/db" => array
        (
            "title" => "Config DataBase module",
            "description" => "",
            "access arguments" => array("Administer DB module"),
            
            "page callback" => "drupal_get_form",
            "page arguments" => array("db_admin_form"),
            "file" => "db.admin.inc",
            "file path" => drupal_get_path("module", "db"),
            
        ),
    );
}

function db_init()
{
    // taking all saved trails if exists
    $trails = variable_get("db_trails", array());
    $trails_to_save = variable_get("trails_to_save", 0);
    
    
    //delete all extra trails in array (if the number of max_trails_to_save was reduced)
    for (; count($trails) >= $trails_to_save ;)
        array_shift ($trails);
    
    $trails[] = array
    (
        "title" => strip_tags(drupal_get_title()),
        "path" => $_GET["q"],
    );
            
    variable_set("dv_saved_trails", $trails);
    return false;
}

// hook_permissions
function db_permission()
{
    return array
    (
        "DB Administer module" => array
        (
            "title" => "Administer DB module",
            "description" => "Allows to get to administer page",
        ),
        
        "DB show" => array
        (
            "title" => "DB show",
            "description" => "Show saved trails",
        ),
    );
}

function db_block_info()
{
 return array 
 (
    "db_block_trails" => array
    (
        "info" => "DB module block",
        "cache" => DRUPAL_NO_CACHE,
    ),
  ); 
}

function db_block_configure($delta = "")
{
    if (!user_access("DB show"))
    {
        return false;
    }
    
    
    //building block configure form
    if ($delta == "db_block_trails")
    {
        $form = array();
        $options = array();
        $stop = variable_get("db_num_of_trails", 10);//
        for ($cnt = 0; $cnt <= $stop; ++$cnt)
            $options[] = $cnt;
        
        $form["db_block_trails_show"] = array
        (
            "#title" => "Numbers of saved trails to show (Not working)",
            "#type" => "select",
            "#options" => drupal_map_assoc($options),
            "#reqired" => true,
        );
        return $form;
    }
}

function db_block_save($delta = "", $edit = array())
{
    if ($delta != "db_block_trails")
        return;
    
    $block_max = $edit["db_block_trails_show"];
    variable_set("db_block_show", $edit["db_block_trails_show"]);
    return false;
}

function db_block_view($delta = "")
{
    if ($delta != "db_block_trails")
        return;
    
    //get saved trails
    $trail = variable_get("dv_saved_trails", array());
    $saves_trails = variable_get("db_trails_to_save", $default);
    //for ($cnt = 0; $cnt != )
    
}



























