<?php

include_once './sites/all/libraries/custom/hooks/menu.php';

function db_menu()
{
    
    return array
    (
        "admin/config/db" => array
        (
            "title" => "Config DataBase module",
            "description" => "",
            "access arguments" => array("Administer DB module"),
            
            "page callback" => "drupal_get_form",
            "page arguments" => array("db_admin_form"),
            "file" => "db.admin.inc",
            "file path" => drupal_get_path("module", "db"),
            
        ),
    );
}

function db_init()
{
    global $user;
    // taking all saved trails if exists
    $trails = variable_get("db_saved_trails", array());
    $trails_to_save = variable_get("db_trails_to_save", 0);
   
    // select all trails of this user
    $res = db_select("db_trails", "t")
            ->fields("t")
            ->condition("user_id", $user->uid, "=")
            ->orderBy("time_stamp", "DESC")
            ->execute();
    $res_array = array();
    foreach ($res as $row)
        $res_array[] = $row;
    
    for ($cnt = 0; $trails_to_save <= count($res_array); ++$cnt)
    
    
    
    $link = $GLOBALS["base_path"];
    
    //delete all extra trails in array (if the number of max_trails_to_save was reduced)
    for (; count($trails) != 0 && count($trails) >= $trails_to_save ;)
    {
        array_shift ($trails);
    }
    
    $trails[] = array
    (
        "title" => strip_tags(drupal_get_title()),
        "path" => $_GET["q"],
    );
    
    variable_set("db_saved_trails", $trails);
    return false;
}

// hook_permissions
function db_permission()
{
    return array
    (
        "DB Administer module" => array
        (
            "title" => "Administer DB module",
            "description" => "Allows to get to administer page",
        ),
        
        "DB show" => array
        (
            "title" => "DB show",
            "description" => "Show saved trails",
        ),
    );
}

function db_block_info()
{
 return array 
 (
    "db_block_trails" => array
    (
        "info" => "DB module block",
        "cache" => DRUPAL_NO_CACHE,
    ),
  ); 
}

function db_block_configure($delta = "")
{
    if (!user_access("DB show"))
    {
        return false;
    }
    
    
    //building block configure form
    if ($delta == "db_block_trails")
    {
        $form = array();
        $options = array();
        
        //$stop = variable_get("db_num_of_trails", 10);//
        
        //how much trails to save. Variable sets in module/admin form
        $stop = variable_get("db_trails_to_save", 10);//
        
        //creating array. The block can't show more trails that saved in module/admin form
        for ($cnt = 0; $cnt <= $stop; ++$cnt)
        {
            $options[] = $cnt;
        }
        
        // this form will set how much trails to show //
        
        
        // if the number of saved trails was reduced after block configuration
        // the number of showed trails in the block can't be larger
        // than number of saved trails
        $db_trails_show = variable_get("db_block_trails_show");
        $default_value = ($db_trails_show > $stop)? $stop : $db_trails_show;
        $form["db_block_trails_show"] = array
        (
            "#title" => "Numbers of saved trails to show (Not used)",
            "#type" => "select",
            "#options" => drupal_map_assoc($options),
            "#default_value" => variable_get("db_block_trails_show", $stop), //$stop - trails to save
            "#reqired" => true,
        );
        return $form;
    }
}

function db_block_save($delta = "", $edit = array())
{
    if ($delta != "db_block_trails")
        return;
    
    $block_max = $edit["db_block_trails_show"];
    variable_set("db_block_show", $edit["db_block_trails_show"]);
    return false;
}

function db_block_view($delta = "")
{   
    if ($delta != "db_block_trails")
        return;
    
    $block["subject"] = "DB block";
    $block["content"] = "<ul>";
    
    //permisstion to see this block
    if (!user_access("DB show"))
    {
         $block["content"] = "access denied";
         return $block;
    }
    
    //get saved trails
    $trail = variable_get("db_saved_trails", array());
    $trail = array_reverse($trail);
    $stop = count($trail);
    for ($cnt = 0; $cnt != $stop; ++$cnt)
    {
        $block["content"] .= "<li>"
       . l($trail[$cnt]["title"], $trail[$cnt]["path"])."</li>";
    }
    return $block;
}



























