<?php

function look_menu()
{
    return array
    (
        "look/theming/example" => array
        (
            "title" => "Theming examples",
            "description" => "It's comtains simple examples of theming",
            "page callback" => "look_theming_example",
            "access arguments" => array("access content"),
        ),
    );
}

function look_theming_example()
{
    // simple output string 
    $output = "<h2>Simple list</h2>";
    $items_list = array();
    $items_list[] = "Go to <code> Configuration > Development > Preformance </code>";
    $items_list[] = "Clear the caches";
    $items_list[] = "Or just visit <code>admin/config/development/performance</code>";
    
    $output .= theme("item_list", array("items" => $items_list));
    
    
    //create an ordered list
    $output .= "<h2>Simple (ordered) list</h2>";
    $items_list[] = "Go to <code> Configuration > Development > Preformance </code>";
    $items_list[] = "Clear the caches";
    $items_list[] = "Or just visit <code>admin/config/development/performance</code>";
    
    $output .= theme("item_list", array
        (
            "items" => $items_list,
            "type" => "ol",
            "title" => t("How to clear the cache"),
        ));
    
    
    //creating simple table with theme function
    $output .= "<h2>Create a simple table</h2>";
    $head = array(t("links"), t("description"));
    $rows = array();
    $rows[] = array(l("Google", "google.com"), "this is a google");
    $rows[] = array(l("Yahoo", "yahoo.com"), "this is a yahoo");
    $rows[] = array(l("NRG", "nrg.co.il"), "Maariv news");
    
    $output .= theme("table", array("header" => $head, "rows" => $rows));
    
    
    //part for implements own theme function
    $p = array();
    $p["vars"][] = "One";
    $p["vars"][] = "Two";
    $p["vars"][] = "Theree";
    
    $output .= "<h2>inplements own theme</h2>";
    $output .= theme("look_p", $p);
    
    
    //using own template (function look_p)
    $variables["strings"] = $p;
    $output .= theme("look_p_2", $variables);
    
    
    return $output;
}

// implements of own theme function
// this function receiving elements
// and wraps every item in <p> element
// Note: every theming function have to start with "theme_"
function theme_look_p($variables)
{
    $d = drupal_get_css();
    
    $d = drupal_add_css(drupal_get_path("module", "look"). "/look.css");
    
    $d = drupal_get_css();
    
    
    // printing the array $vars? that added in module_preprocess_hook
    $str = "";
    foreach ($variables["vars"] as $key => $value)
    {
        //$str .= "<p style = 'color: white; background-color: green;'>".$variables["vars"][$key]."</p>";
        $str .= "<p class='myClass'>".$variables["vars"][$key]."</p>";
    }
    
    return $str;
}

//hook_theme - register every theme function
// every function that registered becomes to HOOK for theme
function look_theme()
{
    return array
    (
        "look_p" => array // the key is name of the theme function (this case it will be: "theme_look_p")
        (
            "variables" => array("vars" => array()), //default variables that function gets
        ),
        
        // example of using theme templetes
        "look_p_2" => array
        (
            "variables" => array("strings" => array()),
            "template" => "my_template", // this is the name of the template file (my_template.tpl.php)
        ),
    );
}

// Implements MODULE_prerocess_HOOK()
function look_preprocess_item_list(&$variables)
{
    return;
}


function look_preprocess_look_p(&$var)
{
    // preprocessing hook adds "theme hook suggestions" array.
    // so need to delete it, or ()more perferred use some storege array in $var
    // $var["variables for function"][0], [1] [2]
    // and get all neccessary variables from there
    
    //drupal_add_css(drupal_get_path("module", "look"). "/look.css");
   // array_pop($var); //delete "theme hook suggestions"
    $var["vars"][] = "Added in preprocess HOOK.";
    
}



































