<?php
// implements hook_init().
function trails_init()
{
        //tacking what we have in trail_history variable
        // if the variable doesn't exists
        //function will return an empty array 
    
    $trails_history = "trails_history";
    $trail = variable_get($trails_history, array());
    
    $num = variable_get("trails_admin_menu", 5);
    $cnt = count($trail);
    
    for (; count($trail) >= $num; array_shift($trail));
    
    $trail[] = array
    (
        "title" => strip_tags(drupal_get_title()), //delete all HTML tags if exists
        "path" => $_GET["q"], //taking the path from q var
        "time" => REQUEST_TIME
    );
    variable_set($trails_history, $trail); //setting new variable
     
    return;
}

function trails_permission()
{
    // this hook returns permissions names
    // after that we be able to check them in
    // "access arguments" => array() for somwe page.
    return array
    (
        "trails administer" => array
        (
            "title" => t("Administer trails module"),
            "description" => t("Add one more permission")
        ),
        
        "trails view" => array
        (
            "title" => t("Access trails blocks"),
            "description" => t("View block generaget by the Trails module")
        )
    );
}

function trails_menu()
{
    
    $items["admin/config/trails"] = array    
    (
        
        "title" => "Trails administer",
        "description" => "Trails module administer",
        "access arguments" => array("trails administer"),
        "page callback" => "drupal_get_form",
        "page arguments" => array("trails_admin_menu"),
        "file" => "trails.admin.inc",
        "file path" => drupal_get_path("module", "trails")
    );
    return $items;
}


function  trails_cron()
{
    // this function will run with the cron (manualy or automaticaly)
    // it can do any actions for this (maybe not only) module
}

// Block hooks
function trails_block_info()
{
    $block = array();
    
    //the index of array is the name of block
    $block["Trails history"] = array
    (
        //info - is single request parametr
        "info" => t("History of trails"),
        "cache" => DRUPAL_NO_CACHE
    );   
    return $block;
}

function trails_block_configure($delta = "")
{
    $form = array();
    $res = user_access("d");
    if (!user_access("a"))
    {
        return;
    }
    
    //$delta id a name of some block. That means - we can create different 
    //menu forms for different blocks
    if ($delta == "Trails history")
    {
        // max number or trails from form in menu hook
        $max_trails = variable_get("trails_admin_menu", 5);
        
        $form["trails_block_num"] = array
        (
            "#type" => "select",
            "#title" => t("Number of trails to show"),
            "#options" => array(range(1, $max_trails, 1)),
            "#default_value" => variable_get("trails_block_num", $max_trails),

            "#options" => drupal_map_assoc(range(1, $max_trails))
        );
    }
    return $form;
}

function trails_block_save($delta = "", $edit = array())
{
    /* $delta contains the name of the block
     * $edit array contains values of form element
     */
    if ($delta == "Trails history")
    {
        variable_set("trails_block_num", $edit["trails_block_num"]);
    }
    return;
}

function trails_block_view($delta = "")
{

    if (!user_access("trails_view") || $delta != "Trails history")
    {
        return;
    }
 
        //receiving trails history array 
    $trails_history = variable_get("trails_history", false);
    $module_array_length = variable_get("trails_admin_menu");
    if (!$trails_history)
    {
        return;
    }
    
    $trails_history = array_reverse($trails_history);
    $block_count = variable_get("trails_block_num", $module_array_length);
    $output = "";
    for($cnt = 0; $cnt != $block_count; ++$cnt)
    {
        if (!isset($trails_history[$cnt]))
        {
            continue;
        }
        
        $item = $trails_history[$cnt];
        $output .= "<li>" . l($item["title"], $item["path"])." " . format_interval(REQUEST_TIME - $item["time"]) . " ".t("ago") . "</li>";
    }
        
        if ($output != "")
        {
            $output .= t("This is the last !num pages you've visited", array("!num", $block_count));
            $output = "<ul>".$output."/ul";
        }
        
        $block["subject"] = "Trails history";
        $block["content"] = $output;
        return $block;
    
    
    
    
}
























